#!/bin/sh
. /lib/lsb/init-functions

case "${1}" in
   start)
      log_info_msg "Starting dhcpcd..."
      start_daemon /sbin/dhcpcd
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping dhcpcd..."
      killproc /sbin/dhcpcd
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart}"
      exit 1
      ;;
esac

exit 0
