#!/bin/sh
. /lib/lsb/init-functions

case "${1}" in
   start)
      log_info_msg "Starting elogind..."
      start_daemon /usr/lib/elogind/elogind --daemon
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping elogind..."
    # if it is possible to use killproc
      killproc /usr/lib/elogind/elogind
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart}"
      exit 1
      ;;
esac

exit 0
