# /etc/profile
export LANG=C.UTF-8

# Append "$1" to $PATH when not already in.
# This function API is accessible to scripts in /etc/profile.d
append_path () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}

append_path '/opt/rustc/bin'
append_path '/usr/local/go/bin'
append_path '/usr/local/sbin'
append_path '/usr/local/bin'
append_path '/usr/bin'

export PATH
