[directory]
style = '#333333'

[character]
success_symbol = '[>](#4A4A4A)'
error_symbol = '[>](#F85552)'
vicmd_symbol = '[<](#4A4A4A)'

[git_branch]
style = '#686868'

[git_commit]
style = '#686868'

[git_state]
style = '#686868'

[git_status]
style = '#686868'

[cmd_duration]
style = '#545454'

[python]
style = '#686868'

[c]
style = '#686868'

[rust]
style = '#686868'

[lua]
style = '#686868'
